# -*- coding: utf-8 -*-
"""ProyectoMod1_Hackaton.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jZvAUlUFDIdB8GmlGSZ1t3zecNFjHp3k
"""

# --------------------- Instalaciones ---------------------
!pip install groq --quiet

!pip install gradio --quiet

!pip install gdown --quiet

# --------------------- Librerias ---------------------
from groq import Groq
from google.colab import userdata
import gdown
import json
import re
import os, json
from typing import Optional

import gradio as gr
import base64
import mimetypes

# --------------------- Cliente Groq ---------------------
client = Groq(api_key=userdata.get('groq_api_key'))     # Inicializar cliente Groq usando secreto
print("Cliente Groq inicializado.")

# Obtener los archivos de mi drive usando enlaces publicos
"""
Este paso es de vital importancia ya que si no se tienen los archivos que usa
la aplicación no se puede continuar.
Esta va a descargar 3 archivos: equivalencias.json, recetas.json y imgbg.png y
los dejara en el directorio /content.
La url de mi drive tiene permisos para que cualquiera con el enlace pueda
leer los archivos.
"""

!pip install gdown --quiet

import gdown

DATA_DIR = "/content"

FOLDER_URL = "https://drive.google.com/drive/folders/1o4R584XeJsC_3AF_BH0EVCJv-3DcTfGy?usp=sharing"

gdown.download_folder(
    url=FOLDER_URL,
    output=DATA_DIR,
    quiet=False,
    use_cookies=False,
)

print("  ---->  Archivos descargados en:")
print(os.listdir(DATA_DIR))

# --------------------- Cargar documentos RAG ---------------------

""" Estos archivos JSON contienen las equivalencias de alimentos y las recetas previamente
 procesadas. Se cargan en memoria para construir índices de búsqueda y recuperación de información. """

RUTA_EQ = "/content/equivalencias.json"
RUTA_REC = "/content/recetas.json"

# Verificación previa
for ruta in (RUTA_EQ, RUTA_REC):
    if not os.path.exists(ruta):
        raise FileNotFoundError(
            f"No se encontró {ruta}.\n"
            f"Contenido actual de /content: {os.listdir('/content')}\n"
        )

with open(RUTA_EQ, "r", encoding="utf-8") as f:
    equivalencias_full = json.load(f)
    equivalencias = equivalencias_full["equivalencias"]
with open(RUTA_REC, "r", encoding="utf-8") as f:
    recetas_full = json.load(f)
    recetas = recetas_full["recetas"]

print("Archivos cargados correctamente, el proceso puede continuar.")

# ---------- Validando carga de equivalencias ----------
print("Tipo de equivalencias:", type(equivalencias))
print("Total equivalencias:", len(equivalencias))
print()
print("Primeras 3 equivalencias:")
print(json.dumps(equivalencias[:3], indent=2, ensure_ascii=False))
print()

# ---------- Validando carga de recetas ----------
print(f"Categorías y cantidad de recetas: {list(recetas.keys())}")
for cat, lista in recetas.items():
    print(f"   - {cat}: {len(lista)} recetas")

# --------------------- Índices ---------------------
# Índice de equivalencias por nombre normalizado
def normalizar(texto: str) -> str:
    """ quitando minúsculas, acentos y signos."""
    texto = texto.lower()
    reemplazos = {"á":"a","é":"e","í":"i","ó":"o","ú":"u","ñ":"n","ü":"u"}
    for k, v in reemplazos.items():
        texto = texto.replace(k, v)
    texto = re.sub(r"[^a-z0-9\s]", " ", texto)
    return re.sub(r"\s+", " ", texto).strip()

# Índice de equivalencias: nombre normalizado -> objeto
idx_equivalencias = {normalizar(e["alimento"]): e for e in equivalencias}

# Índice de recetas: id -> objeto
idx_recetas = {}
for cat, lista in recetas.items():
    for r in lista:
        idx_recetas[r["id"]] = {**r, "categoria": cat}

# Índice invertido: ingrediente normalizado -> lista de recetas que lo usan
idx_ingrediente_a_recetas = {}
for rid, r in idx_recetas.items():
    for ing in r["ingredientes"]:
        key = normalizar(ing["alimento"])
        idx_ingrediente_a_recetas.setdefault(key, []).append(rid)

print(f"Equivalencias indexadas: {len(idx_equivalencias)}")
print(f"Recetas indexadas: {len(idx_recetas)}")
print(f"Ingredientes únicos en recetas: {len(idx_ingrediente_a_recetas)}")

# --------------------- Buscadores ---------------------
def buscar_equivalencias(query: str, top_k: int = 10) -> list[dict]:
    """Busca equivalencias por coincidencia de palabras."""
    q = normalizar(query)
    palabras = q.split()
    resultados = []
    for key, eq in idx_equivalencias.items():
        score = sum(1 for p in palabras if p in key)
        if score > 0:
            resultados.append((score, eq))
    resultados.sort(key=lambda x: -x[0])
    return [eq for _, eq in resultados[:top_k]]


def buscar_recetas_por_ingrediente(ingrediente: str, top_k: int = 10) -> list[dict]:
    """Devuelve recetas que contienen el ingrediente."""
    key = normalizar(ingrediente)
    ids = []
    for k, v in idx_ingrediente_a_recetas.items():
        if key in k:
            ids.extend(v)
    ids = list(dict.fromkeys(ids))[:top_k]  # únicos, preservando orden
    return [idx_recetas[i] for i in ids]


def buscar_recetas_por_categoria(categoria: str) -> list[dict]:
    """Devuelve todas las recetas de una categoría."""
    cat = categoria.strip()   # limpiar espacios
    # Aceptar variantes: camelCase, espacios, etc.
    mapa = {
        "desayuno": "desayuno",
        "colacionmatutina": "colacionMatutina",
        "colacion matutina": "colacionMatutina",
        "comida": "comida",
        "cena": "cena",
        "colacionnocturna": "colacionNocturna",
        "colacion nocturna": "colacionNocturna",
    }
    key = normalizar(cat).replace(" ", "")
    cat_real = mapa.get(key) or mapa.get(normalizar(cat))
    if cat_real and cat_real in recetas:
        return [{**r, "categoria": cat_real} for r in recetas[cat_real]]
    return []


def buscar_recetas_por_nombre(nombre: str, top_k: int = 5) -> list[dict]:
    """Busca recetas por coincidencia en el nombre."""
    q = normalizar(nombre)
    palabras = q.split()
    resultados = []
    for rid, r in idx_recetas.items():
        nombre_norm = normalizar(r["nombre"])
        score = sum(1 for p in palabras if p in nombre_norm)
        if score > 0:
            resultados.append((score, r))
    resultados.sort(key=lambda x: -x[0])
    return [r for _, r in resultados[:top_k]]

# --------------------- Formateadores ---------------------
def formatear_equivalencia(eq: dict) -> str:
    return f"- {eq['alimento']}: {eq['cantidad']} (grupo: {eq['grupo']})"


def formatear_receta(r: dict) -> str:
    lines = [f"### {r['nombre']} (id: {r['id']}, categoría: {r.get('categoria','?')})"]
    lines.append("Intercambios: " + ", ".join(f"{k}={v}" for k, v in r["intercambios"].items()))
    lines.append("Ingredientes:")
    for ing in r["ingredientes"]:
        lines.append(f"  - {ing['alimento']} x{ing['cantidadPorcion']} porción(es)")
    lines.append("Preparación:")
    for paso in r["preparacion"]:
        lines.append(f"  - {paso}")
    lines.append(f"Tiempo: {r['tiempo_preparacion_min']} min | Porciones: {r['porciones']}")
    return "\n".join(lines)

# --------------------- Pipeline RAG ---------------------
def recuperar_contexto(pregunta: str) -> tuple[str, list[dict], list[dict]]:
    """
    Devuelve (contexto_texto, recetas_recuperadas, equivalencias_recuperadas)
    """
    q_norm = normalizar(pregunta)
    recetas_rec = []
    eq_rec = []

    # 1) ¿Pregunta por una categoría?
    categorias_detectadas = []
    for cat in ["desayuno", "colacion matutina", "colacionmatutina",
                "comida", "cena", "colacion nocturna", "colacionnocturna"]:
        if cat in q_norm:
            categorias_detectadas.append(cat)
    for cat in categorias_detectadas:
        recetas_rec.extend(buscar_recetas_por_categoria(cat))

    # 2) ¿Pregunta por un ingrediente?
    # Extraemr palabras "contenido" comunes
    stopwords = {"que","con","sin","para","como","receta","recetas","dame",
                 "muestrame","opciones","tengo","puedo","hacer","usar",
                 "el","la","los","las","un","una","de","del","en","y","o",
                 "preparar","preparacion","ingredientes","cantidad","cantidades"}
    palabras = [p for p in q_norm.split() if p not in stopwords and len(p) > 2]

    for p in palabras:
        eqs = buscar_equivalencias(p, top_k=3)
        eq_rec.extend(eqs)
        recs = buscar_recetas_por_ingrediente(p, top_k=5)
        recetas_rec.extend(recs)

    # 3) ¿Pregunta por nombre específico de receta?
    recetas_rec.extend(buscar_recetas_por_nombre(pregunta, top_k=3))

    # Validar que ya se haya visto la receta o equivalencia para evitar duplicados
    vistos = set()
    recetas_final = []
    for r in recetas_rec:
        if r["id"] not in vistos:
            vistos.add(r["id"])
            recetas_final.append(r)

    # Validar que ya se haya visto un tipo de alimento para evitar duplicados
    vistos_eq = set()
    eq_final = []
    for e in eq_rec:
        if e["alimento"] not in vistos_eq:
            vistos_eq.add(e["alimento"])
            eq_final.append(e)

    # Recortar para no saturar el contexto
    recetas_final = recetas_final[:8]
    eq_final = eq_final[:15]

    # Construir texto de contexto
    partes = []
    if eq_final:
        partes.append("EQUIVALENCIAS RELEVANTES:\n" +
                      "\n".join(formatear_equivalencia(e) for e in eq_final))
    if recetas_final:
        partes.append("RECETAS RELEVANTES:\n" +
                      "\n\n".join(formatear_receta(r) for r in recetas_final))

    contexto = "\n\n".join(partes) if partes else "No se encontró contexto relevante."
    return contexto, recetas_final, eq_final

# Funcion principal que responde las preguntas

def preguntar(pregunta: str, modelo: str = "llama-3.1-8b-instant") -> str:
    contexto, recetas_rec, eq_rec = recuperar_contexto(pregunta)

    system_prompt = """Eres un asistente nutricional experto en el plan de alimentación del usuario.
Respondes en español, de forma clara y concisa.
Solo usas la información del CONTEXTO proporcionado. Si algo no está en el contexto, dilo explícitamente.
Cuando des una receta, incluye: nombre, ingredientes con porciones, preparación paso a paso, tiempo estimado e intercambios.
Cuando des equivalencias, indica el alimento, la cantidad y el grupo."""

    user_prompt = f"""CONTEXTO:
{contexto}

PREGUNTA DEL USUARIO:
{pregunta}
"""

    respuesta = client.chat.completions.create(
        model=modelo,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        temperature=0.3,
        max_tokens=1500,   # si las respuestas son muy largas, aumentar este valor
    )
    return respuesta.choices[0].message.content

# --------------------- Catálogo de recetas ---------------------

def etiqueta_categoria(cat):
    nombres = {
        "desayuno": "Desayuno",
        "colacionMatutina": "Colación matutina",
        "comida": "Comida",
        "cena": "Cena",
        "colacionNocturna": "Colación nocturna",
    }
    return nombres.get(cat, cat)


CATALOGO_LABEL_A_ID = {}

for rid, receta in idx_recetas.items():
    etiqueta = f"{receta['nombre']} · {etiqueta_categoria(receta.get('categoria', '?'))} · {rid}"
    CATALOGO_LABEL_A_ID[etiqueta] = rid


CATEGORIAS_FRONT = ["Todas"] + [
    etiqueta_categoria(cat)
    for cat in recetas.keys()
]


def obtener_recetas_catalogo(categoria_label="Todas"):
    opciones = []

    for rid, receta in idx_recetas.items():
        cat = receta.get("categoria", "?")

        if categoria_label != "Todas" and etiqueta_categoria(cat) != categoria_label:
            continue

        etiqueta = f"{receta['nombre']} · {etiqueta_categoria(cat)} · {rid}"
        opciones.append(etiqueta)

    return sorted(opciones)


def obtener_receta_desde_etiqueta(etiqueta):
    if not etiqueta:
        return None

    rid = CATALOGO_LABEL_A_ID.get(etiqueta)
    if not rid:
        return None

    return idx_recetas.get(rid)


def resumen_receta_catalogo(etiqueta):
    receta = obtener_receta_desde_etiqueta(etiqueta)

    if not receta:
        return "Selecciona una receta para ver su información."

    ingredientes = "\n".join(
        f"- {ing['alimento']} x{ing['cantidadPorcion']} porción(es)"
        for ing in receta["ingredientes"]
    )

    intercambios = ", ".join(
        f"{k}={v}"
        for k, v in receta["intercambios"].items()
    )

    return f"""
### {receta['nombre']}

**Categoría:** {etiqueta_categoria(receta.get("categoria", "?"))}
**Tiempo estimado:** {receta['tiempo_preparacion_min']} min
**Porciones:** {receta['porciones']}

**Ingredientes:**

{ingredientes}

**Intercambios:** {intercambios}
"""


def actualizar_catalogo(categoria_label):
    opciones = obtener_recetas_catalogo(categoria_label)

    if not opciones:
        return (
            gr.update(choices=[], value=None),
            "No encontré recetas para esta categoría.",
        )

    primera = opciones[0]

    return (
        gr.update(choices=opciones, value=primera),
        resumen_receta_catalogo(primera),
    )


def preguntar_sobre_receta(pregunta, receta_etiqueta, modelo="llama-3.1-8b-instant"):
    receta = obtener_receta_desde_etiqueta(receta_etiqueta)

    if not receta:
        return preguntar(pregunta, modelo=modelo)

    contexto_receta = formatear_receta(receta)

    system_prompt = """Eres un asistente nutricional experto en el plan de alimentación del usuario.
Respondes en español, de forma clara y concisa.
El usuario eligió una receta específica del catálogo.
Prioriza esa receta para responder.
Si la pregunta requiere información que no está en la receta seleccionada, dilo explícitamente.
Cuando hables de ingredientes, porciones, preparación, tiempo o intercambios, usa únicamente la información del contexto."""

    user_prompt = f"""RECETA SELECCIONADA:
{contexto_receta}

PREGUNTA DEL USUARIO:
{pregunta}
"""

    respuesta = client.chat.completions.create(
        model=modelo,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        temperature=0.3,
        max_tokens=1500,
    )

    return respuesta.choices[0].message.content

# Validar que modelos estan disponibles
modelos = client.models.list()
for m in modelos.data:
    print(m.id)

# --------------------- Probar ---------------------
pruebas = [
    "¿Cuántos gramos es una porción de pechuga de pollo?",
    "Receta de tostadas de atún",
    "¿Qué puedo cenar que tenga queso panela?",
    "Dame una colación nocturna con atún",
]

# Cambiar índice para probar diferentes preguntas
preg = pruebas[0]
print("=" * 70)
print(f"PREGUNTA: {preg}")
print("-" * 70)
print(preguntar(preg, "openai/gpt-oss-20b"))
print()

"""Hasta este punto, tengo listo el agente que va a responder de acuerdo al RAG y solo hay que invocarlo usando la funcion **preguntar** y mandando la pregunta y el modelo.
Lo que sigue es crear la parte visual para que sea mas sencillo para el usuario interactuar con el agente, para eso usare Gradio.
"""

# --------------------- Front Gradio ---------------------

#  Imagen para bg
HERO_IMAGE_PATH = "/content/imgbg.png"

def archivo_a_data_uri(path):
    if not os.path.exists(path):
        print(f"No encontré la imagen en {path}. El diseño cargará sin imagen.")
        return ""

    mime = mimetypes.guess_type(path)[0] or "image/png"

    with open(path, "rb") as f:
        encoded = base64.b64encode(f.read()).decode("utf-8")

    return f"data:{mime};base64,{encoded}"


HERO_IMAGE_DATA = archivo_a_data_uri(HERO_IMAGE_PATH)
HERO_BACKGROUND = f'url("{HERO_IMAGE_DATA}")' if HERO_IMAGE_DATA else "none"


# --------------------- Modelos ---------------------
MODELOS_NO_CHAT = (
    "whisper",
    "prompt-guard",
    "safeguard",
    "orpheus",
    "tts",
    "audio",
)

MODELOS_FRONT = sorted([
    m.id
    for m in modelos.data
    if not any(bloqueado in m.id.lower() for bloqueado in MODELOS_NO_CHAT)
])

if not MODELOS_FRONT:
    MODELOS_FRONT = ["openai/gpt-oss-20b"]

MODELO_DEFAULT = (
    "openai/gpt-oss-20b"
    if "openai/gpt-oss-20b" in MODELOS_FRONT
    else MODELOS_FRONT[0]
)


# --------------------- Tema ---------------------
tema_front = gr.themes.Base(
    primary_hue=gr.themes.colors.lime,
    secondary_hue=gr.themes.colors.emerald,
    neutral_hue=gr.themes.colors.slate,
    font=[gr.themes.GoogleFont("Inter"), "system-ui", "sans-serif"],
).set(
    body_background_fill="#0e1711",
    body_text_color="#f4fff6",
    block_background_fill="transparent",
    block_border_width="0px",
    block_shadow="none",
    input_background_fill="#17231b",
    input_border_color="#334638",
    input_border_width="1px",
    button_primary_background_fill="#79f24f",
    button_primary_background_fill_hover="#66dd3e",
    button_primary_text_color="#101611",
)


# --------------------- CSS ---------------------
custom_css = f"""
.gradio-container {{
    max-width: 1100px !important;
    margin: 0 auto !important;
    padding: 28px !important;
    min-height: 100vh;
    background:
        radial-gradient(circle at top left, rgba(121, 242, 79, 0.18), transparent 28%),
        linear-gradient(135deg, #102017 0%, #07100b 100%);
}}

#app-shell {{
    border-radius: 28px;
    overflow: hidden;
    background: #f7fbf7;
    border: 1px solid rgba(255, 255, 255, 0.10);
    box-shadow: 0 28px 90px rgba(0, 0, 0, 0.38);
}}

#hero-panel {{
    position: relative;
    min-height: 330px;
    padding: 42px 48px;
    overflow: hidden;
    background:
        linear-gradient(90deg, rgba(16, 23, 19, 0.98) 0%, rgba(16, 23, 19, 0.94) 48%, rgba(104, 232, 72, 0.88) 100%);
}}

#hero-panel::after {{
    content: "";
    position: absolute;
    top: 22px;
    right: 28px;
    width: 38%;
    height: 86%;
    background-image: {HERO_BACKGROUND};
    background-repeat: no-repeat;
    background-position: center;
    background-size: contain;
    filter: drop-shadow(0 28px 34px rgba(0, 0, 0, 0.35));
}}

#top-bar {{
    position: relative;
    z-index: 2;
    align-items: center;
    margin-bottom: 34px;
}}

#brand h1 {{
    margin: 0;
    font-size: 30px;
    font-weight: 900;
    color: #ffffff;
}}

#badge p {{
    margin: 0;
    text-align: right;
    color: #d8f8d3;
    font-size: 14px;
    font-weight: 850;
}}

#intro-text {{
    position: relative;
    z-index: 2;
    max-width: 650px;
}}

#intro-text p {{
    margin: 0 0 18px;
    color: #d9e4dc;
    font-size: 18px;
    line-height: 1.5;
    font-weight: 560;
}}

#intro-text strong {{
    color: #ffffff;
    font-weight: 900;
}}

#form-panel {{
    padding: 36px 48px 44px;
    background: #f7fbf7;
}}

#modelo label,
#pregunta label {{
    color: #2d4535 !important;
    font-weight: 850 !important;
    font-size: 15px !important;
}}

#modelo {{
    max-width: 520px;
    margin-bottom: 22px;
}}

#modelo input,
#modelo button,
#modelo .wrap {{
    border-radius: 14px !important;
    background: #ffffff !important;
    color: #203127 !important;
    border-color: #b9d8c2 !important;
}}

#hint p {{
    margin: 8px 0 18px;
    color: #526458;
    font-size: 17px;
    font-weight: 650;
}}

#pregunta textarea {{
    min-height: 155px !important;
    border-radius: 18px !important;
    background: #ffffff !important;
    color: #203127 !important;
    border: 2px solid #67a7ff !important;
    font-size: 17px !important;
    line-height: 1.5 !important;
}}

#pregunta textarea::placeholder {{
    color: #87938b !important;
}}

#acciones {{
    gap: 12px;
    margin-top: 16px;
}}

#enviar {{
    height: 48px;
    border-radius: 14px !important;
    font-size: 17px !important;
    font-weight: 900 !important;
    background: #54b300 !important;
    color: #ffffff !important;
}}

#limpiar {{
    height: 48px;
    border-radius: 14px !important;
    background: #edf2ef !important;
    color: #405147 !important;
    font-weight: 800 !important;
}}

#respuesta {{
    margin-top: 26px;
    padding: 26px 28px;
    border-radius: 20px;
    background: #ffffff;
    border: 1px solid #cfe2d4;
    box-shadow: 0 16px 40px rgba(45, 74, 57, 0.10);
    color: #203127 !important;
}}

#respuesta,
#respuesta * {{
    color: #203127 !important;
    opacity: 1 !important;
}}

#respuesta h1,
#respuesta h2,
#respuesta h3 {{
    color: #143f21 !important;
    font-weight: 900 !important;
}}

#respuesta p,
#respuesta li {{
    font-size: 16px;
    line-height: 1.58;
}}

#respuesta table {{
    width: 100%;
    border-collapse: collapse;
    margin: 18px 0;
    background: #ffffff;
    border: 1px solid #cfe6d3;
}}

#respuesta th,
#respuesta td {{
    border: 1px solid #dcebdd !important;
    padding: 12px 14px !important;
    vertical-align: top;
}}

#respuesta th {{
    background: #e8f7eb !important;
    color: #174522 !important;
    font-weight: 900 !important;
}}

footer {{
    display: none !important;
}}

@media (max-width: 760px) {{
    .gradio-container {{
        padding: 14px !important;
    }}

    #hero-panel {{
        padding: 30px 24px 230px;
    }}

    #hero-panel::after {{
        width: 80%;
        height: 220px;
        top: auto;
        right: 10%;
        bottom: 8px;
    }}

    #form-panel {{
        padding: 28px 24px 34px;
    }}

    #badge p {{
        text-align: left;
    }}
}}
"""


# --------------------- Funciones Front ---------------------
def mensaje_cambiar_modelo(modelo_elegido, detalle=""):
    return f"""
### El modelo seleccionado no alcanza para esta consulta

El modelo **`{modelo_elegido}`** no pudo responder esta pregunta con el contexto recuperado.

Te cambié al modelo recomendado: **`{MODELO_DEFAULT}`**.

{detalle}
"""


def consultar_front(pregunta_usuario, modelo_elegido):
    if not pregunta_usuario or not pregunta_usuario.strip():
        return (
            gr.update(value="Escribe una pregunta para que pueda ayudarte.", visible=True),
            gr.update(),
        )

    modelo_elegido = modelo_elegido or MODELO_DEFAULT
    pregunta_limpia = pregunta_usuario.strip()

    try:
        respuesta = preguntar(pregunta_limpia, modelo=modelo_elegido)
        return (
            gr.update(value=respuesta, visible=True),
            gr.update(),
        )

    except Exception as e:
        return (
            gr.update(
                value=mensaje_cambiar_modelo(
                    modelo_elegido,
                    f"Detalle técnico: `{e}`",
                ),
                visible=True,
            ),
            gr.update(value=MODELO_DEFAULT),
        )


def limpiar_front():
    return "", gr.update(value="", visible=False)


# --------------------- Layout ---------------------
with gr.Blocks(
    title="Asistente nutricional",
    theme=tema_front,
    css=custom_css,
) as demo:

    with gr.Column(elem_id="app-shell"):

        with gr.Column(elem_id="hero-panel"):

            with gr.Row(elem_id="top-bar"):
                with gr.Column(scale=4, elem_id="brand"):
                    gr.Markdown("# Asistente nutricional")

                with gr.Column(scale=1, elem_id="badge"):
                    gr.Markdown("By AIOM")

            gr.Markdown(
                """
Hola, soy un agente que puede ayudarte a seguir un régimen nutricional diseñado para un usuario con características particulares. Para eso uso información sobre ingredientes y sus cantidades por porción, equivalencias y tus recetas previamente definidas.

<strong>¡Empecemos!</strong>

Primero, si eres un usuario experto, puedes elegir el modelo de IA. Si no, no te preocupes, solo salta esta parte y continúa en la sección de preguntas.
                """,
                elem_id="intro-text",
            )

        with gr.Column(elem_id="form-panel"):

            modelo = gr.Dropdown(
                choices=MODELOS_FRONT,
                value=MODELO_DEFAULT,
                label="Modelo de IA",
                info="Lista cargada directamente desde client.models.list()",
                elem_id="modelo",
            )

            gr.Markdown(
                "Ahora sí, dime qué quieres saber. Puedes preguntarme sobre recetas, equivalencias o ingredientes.",
                elem_id="hint",
            )

            pregunta_usuario = gr.Textbox(
                label="Escribe tu pregunta",
                lines=6,
                placeholder="Ej: ¿Qué puedo comer hoy que tenga pollo?",
                elem_id="pregunta",
            )

            with gr.Row(elem_id="acciones"):
                enviar = gr.Button("Enviar", variant="primary", elem_id="enviar", scale=4)
                limpiar = gr.Button("Limpiar", variant="secondary", elem_id="limpiar", scale=1)

            respuesta = gr.Markdown(
                visible=False,
                elem_id="respuesta",
            )

    enviar.click(
        consultar_front,
        inputs=[pregunta_usuario, modelo],
        outputs=[respuesta, modelo],
    )

    pregunta_usuario.submit(
        consultar_front,
        inputs=[pregunta_usuario, modelo],
        outputs=[respuesta, modelo],
    )

    limpiar.click(
        limpiar_front,
        outputs=[pregunta_usuario, respuesta],
    )

demo.launch(debug=True)
